name: Unit Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  BUILD_TYPE: Debug

jobs:
  uint-test:
    # Run on ubuntu
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Install dependencies
      - name: Install dependencies
        run: sudo apt update && sudo apt install liburing-dev openssl libssl-dev libjemalloc-dev lld

      # CMake configuration
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # Build library and tester
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Run the unit test
      - name: Unit Test
        working-directory: ${{github.workspace}}/build
        run: ./tester
